version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
    image: rocketdata_django
    container_name: rocketdata_django
    depends_on:
      - db
    env_file:
      - ./.envs/django
      - ./.envs/postgres
    volumes:
      - .:/rocketdata
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres
    env_file: ./.envs/postgres
    container_name: rocketdata_db
    ports:
      - 55551:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: rocketdata_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - db

    ports: []
    command: celery -A core worker -l INFO

  celerybeat:
    <<: *django
    image: rocketdata_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - db

    ports: []
    command: celery -A core beat -l INFO

volumes:
  postgres_data: