# Generated by Django 3.1.4 on 2020-12-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_employeemptt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemptt',
            name='middle_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='employeemptt',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='employeemptt',
            name='salary',
            field=models.PositiveSmallIntegerField(verbose_name='Salary in $'),
        ),
        migrations.AlterField(
            model_name='employeemptt',
            name='surname',
            field=models.CharField(max_length=35),
        ),
    ]
