# Generated by Django 3.1.4 on 2020-12-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20201206_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemptt',
            old_name='middle_name',
            new_name='patronymic',
        ),
    ]
